### ISSUE TITLE
Add Claude Code GitHub Actions

### ISSUE THREAD

**Issue by galligan** [outfitter-dev/rulesets-old#43]
## Task

Replace the current claude workflow with the `claude.yml` action below

```yml
name: Claude Assistant
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude-response:
    runs-on: ubuntu-latest
    steps:
      - uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Optional: add custom trigger phrase (default: @claude)
          # trigger_phrase: "/claude"
          # Optional: add assignee trigger for issues
          # assignee_trigger: "claude"
```

For this one let's include `/claude` and `@claude` trigger phrases, as well as the assignee trigger.
